Delete two_factor/migrations/0001_squashed_0008_delete_phonedevice.py
This file causes the error below so I deleted it:

> django.db.utils.OperationalError: no such table: two_factor_phonedevice